### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'dist'

### ISSUE THREAD

**Issue by pawopawo** [NoamRosenberg/AutoML#91]
AttributeError: 'Namespace' object has no attribute 'dist' when run` CUDA_VISIBLE_DEVICES=0 python3 train_autodeeplab.py --dataset cityscapes
`

**Comment by kukby** [comment]
I have meet the same problem did you solved?

**Comment by kukby** [comment]
Traceback (most recent call last):
  File "train_autodeeplab.py", line 332, in <module>
    main()
  File "train_autodeeplab.py", line 321, in main
    trainer = Trainer(args)
  File "train_autodeeplab.py", line 47, in __init__
    self.train_loaderA, self.train_loaderB, self.val_loader, self.test_loader, self.nclass = make_data_loader(args, **kwargs)
  File "/root/AutoML-new_master/dataloaders/__init__.py", line 7, in make_data_loader
    if args.dist:
AttributeError: 'Namespace' object has no attribute 'dist'

**Comment by adityalokesh** [comment]
Facing the same issue is it because the dateset is not  loaded correctly or some path issue in mypath.py ? did any one solve this issue pls help !

**Comment by cardwing** [comment]
Please have a look at [this issue](https://github.com/NoamRosenberg/autodeeplab/issues/83).

**Comment by mingfengHuang** [comment]
@kukby Have you solved the problem?Please help!
