### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by kukby** [NoamRosenberg/AutoML#98]
I have meet a problem, Can you solve it? Thanks!
Traceback (most recent call last):
  File "train_autodeeplab.py", line 332, in <module>
    main()
  File "train_autodeeplab.py", line 321, in main
    trainer = Trainer(args)
  File "train_autodeeplab.py", line 47, in __init__
    self.train_loaderA, self.train_loaderB, self.val_loader, self.test_loader, self.nclass = make_data_loader(args, **kwargs)
  File "/home/kukby/AutoML-new_master/dataloaders/__init__.py", line 13, in make_data_loader
    sampler1 = torch.utils.data.distributed.DistributedSampler(train_set1)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 30, in __init__
    num_replicas = dist.get_world_size()
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"

**Comment by ntongzhi** [comment]
I encountered the same problem, how did you solve it？

**Comment by ntongzhi** [comment]
Have you solved the problem?Please help!
